# Generated by Django 3.2.9 on 2021-11-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='color',
            field=models.CharField(default='red', max_length=256),
            preserve_default=False,
        ),
    ]
